// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc7qB5bhWu2ZUqhnVoygVfgk18P_1pJAY',
    appId: '1:700350485401:web:64fc058102a42205fcf908',
    messagingSenderId: '700350485401',
    projectId: 'chatapp-b1a06',
    authDomain: 'chatapp-b1a06.firebaseapp.com',
    storageBucket: 'chatapp-b1a06.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Tp8kYrMlm2O5Qf-sjOfiNyYdI8JuC2s',
    appId: '1:700350485401:android:acff81056b9bc4c1fcf908',
    messagingSenderId: '700350485401',
    projectId: 'chatapp-b1a06',
    storageBucket: 'chatapp-b1a06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcsPZCCkZUqly1ykSj-PF1lxANnLaZdLo',
    appId: '1:700350485401:ios:66b2285343d5748bfcf908',
    messagingSenderId: '700350485401',
    projectId: 'chatapp-b1a06',
    storageBucket: 'chatapp-b1a06.firebasestorage.app',
    iosBundleId: 'com.example.chatAppWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcsPZCCkZUqly1ykSj-PF1lxANnLaZdLo',
    appId: '1:700350485401:ios:66b2285343d5748bfcf908',
    messagingSenderId: '700350485401',
    projectId: 'chatapp-b1a06',
    storageBucket: 'chatapp-b1a06.firebasestorage.app',
    iosBundleId: 'com.example.chatAppWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc7qB5bhWu2ZUqhnVoygVfgk18P_1pJAY',
    appId: '1:700350485401:web:94aa2f7c096771e2fcf908',
    messagingSenderId: '700350485401',
    projectId: 'chatapp-b1a06',
    authDomain: 'chatapp-b1a06.firebaseapp.com',
    storageBucket: 'chatapp-b1a06.firebasestorage.app',
  );
}
